; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = unit_build
src_dir = ./

[env]
monitor_speed = 115200
build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D FEATURES_FILE_ENABLE_ENCRYPTION=1
	-D FEATURES_WIFI_STORAGE_SPIFFS=1
	-D FEATURES_SNTP_ENABLE=1
	-D FEATURES_CUSHY_WEB_SERVER_OTA=1
	-D SETTING_WIFI_STORAGE_OVERRIDE=1
	-D SETTING_DEFAULT_FAVICON=1
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
build_src_filter =
	+<src/>
	-<.git/>
	-<.svn/>
	-<.pio/>
	-<.vscode/>
	-<doxygen/>
	-<test/>
	-<examples/basic>
	+<examples/standard>
	-<examples/advance>

[env:unit_build]
framework = arduino
platform = espressif32
board = m5stack-atom
build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D CORE_DEBUG_LEVEL=5
test_build_src = yes
lib_deps =
	m5stack/M5Atom@^0.1.0
	fastled/FastLED@^3.5.0
	ESP32Async/ESPAsyncWebServer@^3.8.0
	ESP32Async/AsyncTCP
	ayushsharma82/ElegantOTA@^3.1.4
	bblanchon/ArduinoJson@^7.4.2
lib_ignore =
  RPAsyncTCP
  ESPAsyncTCP
lib_compat_mode = strict
lib_ldf_mode = chain
check_tool = cppcheck
check_flags = --enable=all
platform_packages = tool-cppcheck@1.260.0

[env:web_m5stack_atom]
framework = arduino
platform = espressif32
board = m5stack-atom
lib_deps =
	m5stack/M5Atom@^0.1.0
	fastled/FastLED@^3.5.0
	ESP32Async/ESPAsyncWebServer@^3.8.0
	ESP32Async/AsyncTCP
	ayushsharma82/ElegantOTA@^3.1.4
	bblanchon/ArduinoJson@^7.4.2
lib_ignore =
  RPAsyncTCP
  ESPAsyncTCP
lib_compat_mode = strict
lib_ldf_mode = chain

[env:web_m5stack_core_esp32]
framework = arduino
platform = espressif32
board = m5stack-core-esp32
lib_deps =
	m5stack/M5Atom@^0.1.0
	fastled/FastLED@^3.5.0
	ESP32Async/ESPAsyncWebServer@^3.8.0
	ESP32Async/AsyncTCP
	ayushsharma82/ElegantOTA@^3.1.4
	bblanchon/ArduinoJson@^7.4.2
lib_ignore =
  RPAsyncTCP
  ESPAsyncTCP
lib_compat_mode = strict
lib_ldf_mode = chain
